name: Deploy with Maven

on:
  push:
    branches: [production]

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'production'
      - name: Set up JDK 17.0.5
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.5'
          distribution: 'adopt'
      - name: Package with Maven
        run: |
          mvn clean package
          ls
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bedwars-plugin
          path: bedwars-plugin/target/**.jar
          if-no-files-found: error
      - name: Set next version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: [ package ]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'production'
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: bedwars-plugin
          path: target
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          target_commitish: production
          tag_name: ${{ needs.package.outputs.version }}
          generate_release_notes: true
          files: "target/bedwars-*"
  merge-master-back-to-dev:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    needs: [ release ]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'production'
      - name: deploy-lock
        uses: github/lock@v2.0.0
        id: lock
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mode: lock
          environment: master
          environment_targets: master
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge master back to dev
        run: |
          git fetch --unshallow
          git checkout master
          git pull
          git merge --no-ff production -m "Auto-merge production back to master"
          git push --force