name: Deploy snapshot package to BedWars Repo

on:
  push:
    branches: [development, workflow-test]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Deploy package to repo
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'development'
      - name: Set up JDK 17.0.7
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.7'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Deploy Package
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASS: ${{ secrets.REPO_PASS }}
        run: mvn --batch-mode -DskipTests clean deploy -s settings.xml
  javadoc:
    name: Publish JavaDoc
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'development'
      - name: Set up JDK 17.0.7
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.7'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Install Packages
        run: mvn install
      - name: Build JavaDoc
        run: mvn javadoc:javadoc
      - name: Create key for Deploy
        run: |
          echo "${{ secrets.JDC_PRIVATE_KEY }}" > ./id_rsa
      - name: Deploy JavaDoc 🚀
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.JDC_IP_ADDRESS }}
          username: ${{ secrets.JDC_USER }}
          privateKey: './id_rsa'
          localDir: 'bedwars-api/target/site/apidocs'
          remoteDir: '/var/www/tomkeuper.com/javadocs'
          removeExtraFilesOnServer: true