name: Deploy snapshot package to BedWars Repo

on:
  push:
    branches: [development]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Deploy to repo
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'api-fixes'
      - name: Set up JDK 17.0.7
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.7'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Deploy Package
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASS: ${{ secrets.REPO_PASS }}
        run: mvn --batch-mode -DskipTests clean deploy -s settings.xml
      - name: Build JavaDoc
        run: mvn javadoc:javadoc
      - name: Deploy JavaDoc 🚀
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        env:
          JDC_IP_ADDRESS: ${{ secrets.JDC_IP_ADDRESS }}
          JDC_USER: ${{ secrets.JDC_USER }}
          JDC_PRIVATE_KEY: ${{ secrets.JDC_PRIVATE_KEY }}
        with:
          username: ${{env.JDC_USER}}
          server: ${{env.JDC_IP_ADDRESS}}
          ssh_private_key: ${{ env.JDC_PRIVATE_KEY }}
          local_path: './static/*'
          remote_path: '/snapshot-javadocs/'
          sftpArgs: '-o ConnectTimeout=5'